using Newrest.Pos.Domain.Accounts;
using Newrest.Pos.Domain.Common;

namespace Newrest.Pos.Domain.Sales;

public enum TicketKind
{
    Sale,
    CreditNote,
}

public enum LineSource
{
    Manual,
    VisionAuto,
    VisionConfirmed,
    VisionCorrected,
}

public sealed record TicketLineInput(
    Guid ArticleId,
    string ArticleCode,
    string Label,
    int Quantity,
    decimal UnitPrice,
    decimal VatRate,
    bool IsSubsidizable = true,
    LineSource Source = LineSource.Manual);

public sealed record PaymentInput(PaymentMethod Method, decimal Amount)
{
    /// <summary>Cash handed by the diner (cash only).</summary>
    public decimal? Tendered { get; init; }

    /// <summary>Authorisation reference typed from the standalone card terminal (card only).</summary>
    public string? AuthorizationCode { get; init; }

    /// <summary>Ledger movement created for an account payment.</summary>
    public Guid? AccountMovementId { get; init; }
}

public sealed record TicketIssueRequest
{
    /// <summary>Generated by the register; doubles as the sync idempotency key.</summary>
    public required Guid Id { get; init; }
    public required Guid RegisterId { get; init; }
    public required string RegisterPrefix { get; init; }
    public required long Sequence { get; init; }
    public required string PreviousHash { get; init; }
    public required Guid CashSessionId { get; init; }
    public required Guid OperatorId { get; init; }
    public required DateOnly BusinessDate { get; init; }
    public required DateTimeOffset IssuedAt { get; init; }
    public required IReadOnlyList<TicketLineInput> Lines { get; init; }
    public IReadOnlyList<PaymentInput> Payments { get; init; } = [];
    public decimal SubsidyAmount { get; init; }
    public Guid? SubsidyRuleId { get; init; }
    public Guid? DinerId { get; init; }
    public Guid? AccountId { get; init; }
    public string? BadgeNumber { get; init; }
}

public sealed record CreditNoteRequest
{
    public required Guid Id { get; init; }
    public required string RegisterPrefix { get; init; }
    public required long Sequence { get; init; }
    public required string PreviousHash { get; init; }
    public required Guid CashSessionId { get; init; }
    public required Guid OperatorId { get; init; }
    public required DateOnly BusinessDate { get; init; }
    public required DateTimeOffset IssuedAt { get; init; }
    public required string Reason { get; init; }

    /// <summary>How the diner share is given back. Defaults to the original payments negated.</summary>
    public IReadOnlyList<PaymentInput>? RefundPayments { get; init; }
}

/// <summary>
/// Fiscal ticket (sale or credit note). Immutable once issued: corrections are made by issuing a credit note.
/// Amounts are TTC. <c>TotalAmount = SubsidyAmount + DinerShare</c> and the payments sum to <c>DinerShare</c>.
/// </summary>
public sealed class Ticket : Entity, IImmutableRecord
{
    private readonly List<TicketLine> _lines = [];
    private readonly List<Payment> _payments = [];

    private Ticket()
    {
    }

    public Guid RegisterId { get; private set; }
    public TicketKind Kind { get; private set; }
    public long Sequence { get; private set; }
    public string Number { get; private set; } = null!;
    public Guid CashSessionId { get; private set; }
    public Guid OperatorId { get; private set; }
    public DateOnly BusinessDate { get; private set; }
    public DateTimeOffset IssuedAt { get; private set; }
    public Guid? DinerId { get; private set; }
    public Guid? AccountId { get; private set; }
    public string? BadgeNumber { get; private set; }
    public Guid? SubsidyRuleId { get; private set; }
    public Guid? CreditedTicketId { get; private set; }
    public string? CreditReason { get; private set; }
    public decimal TotalAmount { get; private set; }
    public decimal TotalVat { get; private set; }
    public decimal SubsidyAmount { get; private set; }
    public decimal DinerShare { get; private set; }
    public string PreviousHash { get; private set; } = null!;
    public string Hash { get; private set; } = null!;

    /// <summary>Server reception timestamp (set by persistence).</summary>
    public DateTimeOffset ReceivedAt { get; set; }

    public IReadOnlyList<TicketLine> Lines => _lines;
    public IReadOnlyList<Payment> Payments => _payments;

    /// <summary>Sum of subsidizable lines, the base of the employer subsidy.</summary>
    public static decimal EligibleAmount(IEnumerable<TicketLineInput> lines) =>
        lines.Where(l => l.IsSubsidizable).Sum(l => Money.Round(l.UnitPrice * l.Quantity));

    public static decimal ComputeTotal(IEnumerable<TicketLineInput> lines) => lines.Sum(l => Money.Round(l.UnitPrice * l.Quantity));

    public static Ticket Issue(TicketIssueRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        if (request.Lines.Count == 0)
        {
            throw new DomainException("empty_ticket", "A ticket needs at least one line.");
        }

        foreach (var line in request.Lines)
        {
            if (line.Quantity <= 0)
            {
                throw new DomainException("invalid_quantity", "Sale quantities must be positive.");
            }

            Guard.NotNegative(line.UnitPrice, nameof(line.UnitPrice));
        }

        var subsidy = Money.EnsureValid(Guard.NotNegative(request.SubsidyAmount, nameof(request.SubsidyAmount)), nameof(request.SubsidyAmount));
        var total = ComputeTotal(request.Lines);
        if (subsidy > total)
        {
            throw new DomainException("subsidy_exceeds_total", "The subsidy cannot exceed the ticket total.");
        }

        if (subsidy > 0 && request.DinerId is null)
        {
            throw new DomainException("subsidy_without_diner", "A subsidy requires an identified diner.");
        }

        foreach (var payment in request.Payments)
        {
            if (payment.Amount <= 0)
            {
                throw new DomainException("invalid_payment", "Sale payments must be positive.");
            }
        }

        var ticket = Create(request.Id, request.RegisterId, TicketKind.Sale, request.RegisterPrefix, request.Sequence,
            request.CashSessionId, request.OperatorId, request.BusinessDate, request.IssuedAt);
        ticket.DinerId = request.DinerId;
        ticket.AccountId = request.AccountId;
        ticket.BadgeNumber = request.BadgeNumber;
        ticket.SubsidyRuleId = subsidy > 0 ? request.SubsidyRuleId : null;
        ticket.SubsidyAmount = subsidy;
        ticket.AddLines(request.Lines);
        ticket.AddPayments(request.Payments);
        ticket.Seal(request.PreviousHash);
        return ticket;
    }

    /// <summary>Full credit note of <paramref name="original"/>: every line, the subsidy and the payments are negated.</summary>
    public static Ticket IssueCreditNote(Ticket original, CreditNoteRequest request)
    {
        ArgumentNullException.ThrowIfNull(original);
        ArgumentNullException.ThrowIfNull(request);
        if (original.Kind != TicketKind.Sale)
        {
            throw new DomainException("cannot_credit_credit_note", "Only a sale can be credited.");
        }

        var ticket = Create(request.Id, original.RegisterId, TicketKind.CreditNote, request.RegisterPrefix, request.Sequence,
            request.CashSessionId, request.OperatorId, request.BusinessDate, request.IssuedAt);
        ticket.CreditedTicketId = original.Id;
        ticket.CreditReason = Guard.NotBlank(request.Reason, nameof(request.Reason), 500);
        ticket.DinerId = original.DinerId;
        ticket.AccountId = original.AccountId;
        ticket.BadgeNumber = original.BadgeNumber;
        ticket.SubsidyRuleId = original.SubsidyRuleId;
        ticket.SubsidyAmount = -original.SubsidyAmount;
        ticket.AddLines(original.Lines.Select(l => new TicketLineInput(
            l.ArticleId, l.ArticleCode, l.Label, -l.Quantity, l.UnitPrice, l.VatRate, l.IsSubsidizable, l.Source)));

        var refunds = request.RefundPayments ?? original.Payments
            .Select(p => new PaymentInput(p.Method, -p.Amount) { AuthorizationCode = p.AuthorizationCode })
            .ToList();
        foreach (var refund in refunds)
        {
            if (refund.Amount >= 0)
            {
                throw new DomainException("invalid_payment", "Credit note refunds must be negative.");
            }
        }

        ticket.AddPayments(refunds);
        ticket.Seal(request.PreviousHash);
        return ticket;
    }

    /// <summary>Recomputes the hash from the stored content (integrity check).</summary>
    public bool HasValidHash() => TicketHasher.ComputeHash(this) == Hash;

    private static Ticket Create(Guid id, Guid registerId, TicketKind kind, string prefix, long sequence, Guid cashSessionId,
        Guid operatorId, DateOnly businessDate, DateTimeOffset issuedAt) => new()
        {
            Id = Guard.NotEmpty(id, nameof(id)),
            RegisterId = Guard.NotEmpty(registerId, nameof(registerId)),
            Kind = kind,
            Sequence = sequence,
            Number = TicketNumber.Format(prefix, sequence),
            CashSessionId = Guard.NotEmpty(cashSessionId, nameof(cashSessionId)),
            OperatorId = Guard.NotEmpty(operatorId, nameof(operatorId)),
            BusinessDate = businessDate,
            // Millisecond precision keeps the hash stable across every storage engine.
            IssuedAt = new DateTimeOffset(issuedAt.UtcTicks - (issuedAt.UtcTicks % TimeSpan.TicksPerMillisecond), TimeSpan.Zero),
        };

    private void AddLines(IEnumerable<TicketLineInput> lines)
    {
        var number = 1;
        foreach (var input in lines)
        {
            _lines.Add(new TicketLine(Id, number++, input));
        }

        TotalAmount = _lines.Sum(l => l.LineTotal);
        TotalVat = _lines.Sum(l => l.VatAmount);
        DinerShare = TotalAmount - SubsidyAmount;
    }

    private void AddPayments(IEnumerable<PaymentInput> payments)
    {
        var index = 1;
        foreach (var input in payments)
        {
            _payments.Add(new Payment(Id, index++, input, AccountId));
        }

        var paid = _payments.Sum(p => p.Amount);
        if (paid != DinerShare)
        {
            throw new DomainException("payment_mismatch", $"Payments ({paid:0.00}) must equal the diner share ({DinerShare:0.00}).");
        }
    }

    private void Seal(string previousHash)
    {
        PreviousHash = TicketHasher.ValidateHash(previousHash);
        Hash = TicketHasher.ComputeHash(this);
    }
}

public sealed class TicketLine : Entity, IImmutableRecord
{
    private TicketLine()
    {
    }

    internal TicketLine(Guid ticketId, int lineNumber, TicketLineInput input)
    {
        if (input.Quantity == 0)
        {
            throw new DomainException("invalid_quantity", "Quantity cannot be zero.");
        }

        if (input.VatRate is < 0 or >= 1)
        {
            throw new DomainException("invalid_vat_rate", "VAT rate must be a fraction between 0 and 1.");
        }

        TicketId = ticketId;
        LineNumber = lineNumber;
        ArticleId = Guard.NotEmpty(input.ArticleId, nameof(input.ArticleId));
        ArticleCode = Guard.NotBlank(input.ArticleCode, nameof(input.ArticleCode), 32);
        Label = Guard.NotBlank(input.Label, nameof(input.Label), 150);
        Quantity = input.Quantity;
        UnitPrice = Money.EnsureValid(input.UnitPrice, nameof(input.UnitPrice));
        VatRate = input.VatRate;
        IsSubsidizable = input.IsSubsidizable;
        Source = input.Source;
        LineTotal = Money.Round(UnitPrice * Quantity);
        VatAmount = Money.VatFromInclusive(LineTotal, VatRate);
    }

    public Guid TicketId { get; private set; }
    public int LineNumber { get; private set; }
    public Guid ArticleId { get; private set; }
    public string ArticleCode { get; private set; } = null!;
    public string Label { get; private set; } = null!;
    public int Quantity { get; private set; }
    public decimal UnitPrice { get; private set; }
    public decimal VatRate { get; private set; }
    public decimal LineTotal { get; private set; }
    public decimal VatAmount { get; private set; }
    public bool IsSubsidizable { get; private set; }
    public LineSource Source { get; private set; }
}

public sealed class Payment : Entity, IImmutableRecord
{
    private Payment()
    {
    }

    internal Payment(Guid ticketId, int index, PaymentInput input, Guid? ticketAccountId)
    {
        TicketId = ticketId;
        Index = index;
        Method = input.Method;
        Amount = Money.EnsureValid(input.Amount, nameof(input.Amount));
        switch (input.Method)
        {
            case PaymentMethod.Cash when input.Amount > 0:
                var tendered = input.Tendered ?? input.Amount;
                if (tendered < input.Amount)
                {
                    throw new DomainException("insufficient_cash", "Tendered cash is lower than the amount due.");
                }

                Tendered = Money.EnsureValid(tendered, nameof(input.Tendered));
                Change = tendered - input.Amount;
                break;
            case PaymentMethod.Card when input.Amount > 0 && string.IsNullOrWhiteSpace(input.AuthorizationCode):
                throw new DomainException("authorization_required", "A card payment requires the terminal authorisation reference.");
            case PaymentMethod.Account when ticketAccountId is null:
                throw new DomainException("account_required", "An account payment requires an identified account.");
            case PaymentMethod.BankTransfer:
                throw new DomainException("unsupported_payment", "Bank transfers are not accepted at the register.");
        }

        AuthorizationCode = input.AuthorizationCode?.Trim();
        AccountMovementId = input.AccountMovementId;
    }

    public Guid TicketId { get; private set; }
    public int Index { get; private set; }
    public PaymentMethod Method { get; private set; }

    /// <summary>Amount kept (net of change). Negative for credit-note refunds.</summary>
    public decimal Amount { get; private set; }

    public decimal? Tendered { get; private set; }
    public decimal? Change { get; private set; }
    public string? AuthorizationCode { get; private set; }
    public Guid? AccountMovementId { get; private set; }
}
