using Microsoft.EntityFrameworkCore;
using Newrest.Pos.Domain.Accounts;
using Newrest.Pos.Domain.Audit;
using Newrest.Pos.Domain.Catalog;
using Newrest.Pos.Domain.Clients;
using Newrest.Pos.Domain.Common;
using Newrest.Pos.Domain.Menus;
using Newrest.Pos.Domain.Organization;
using Newrest.Pos.Domain.Sales;
using Newrest.Pos.Domain.Vision;

namespace Newrest.Pos.Infrastructure.Persistence;

public sealed class PosDbContext(DbContextOptions<PosDbContext> options) : DbContext(options)
{
    public const string Schema = "pos";

    public DbSet<Company> Companies => Set<Company>();
    public DbSet<Site> Sites => Set<Site>();
    public DbSet<PointOfSale> PointsOfSale => Set<PointOfSale>();
    public DbSet<Register> Registers => Set<Register>();
    public DbSet<Operator> Operators => Set<Operator>();

    public DbSet<Category> Categories => Set<Category>();
    public DbSet<Article> Articles => Set<Article>();
    public DbSet<ArticlePhoto> ArticlePhotos => Set<ArticlePhoto>();
    public DbSet<PriceList> PriceLists => Set<PriceList>();
    public DbSet<PriceOverride> PriceOverrides => Set<PriceOverride>();
    public DbSet<DailyMenu> DailyMenus => Set<DailyMenu>();
    public DbSet<DailyMenuItem> DailyMenuItems => Set<DailyMenuItem>();

    public DbSet<ClientCompany> ClientCompanies => Set<ClientCompany>();
    public DbSet<Contract> Contracts => Set<Contract>();
    public DbSet<SubsidyRule> SubsidyRules => Set<SubsidyRule>();
    public DbSet<Diner> Diners => Set<Diner>();
    public DbSet<Badge> Badges => Set<Badge>();
    public DbSet<Account> Accounts => Set<Account>();
    public DbSet<AccountMovement> AccountMovements => Set<AccountMovement>();

    public DbSet<CashSession> CashSessions => Set<CashSession>();
    public DbSet<Ticket> Tickets => Set<Ticket>();
    public DbSet<TicketLine> TicketLines => Set<TicketLine>();
    public DbSet<Payment> Payments => Set<Payment>();
    public DbSet<ZReport> ZReports => Set<ZReport>();
    public DbSet<ZReportLine> ZReportLines => Set<ZReportLine>();

    public DbSet<RecognitionLog> RecognitionLogs => Set<RecognitionLog>();
    public DbSet<AuditLog> AuditLogs => Set<AuditLog>();

    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        // Money everywhere: decimal(18,2). Rates and percentages override this explicitly.
        configurationBuilder.Properties<decimal>().HavePrecision(18, 2);
        configurationBuilder.Properties<string>().HaveMaxLength(200);

        // Enums are stored as readable strings (stable across reorderings, readable by DBAs and BI).
        var enumTypes = typeof(Entity).Assembly.GetTypes()
            .Where(t => t.IsEnum && !t.IsDefined(typeof(FlagsAttribute), false));
        foreach (var enumType in enumTypes)
        {
            configurationBuilder.Properties(enumType).HaveConversion<string>().HaveMaxLength(32);
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema(Schema);
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(PosDbContext).Assembly);

        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            var clrType = entityType.ClrType;

            // Identifiers are always generated by the domain (offline registers included).
            if (typeof(Entity).IsAssignableFrom(clrType))
            {
                modelBuilder.Entity(clrType).Property(nameof(Entity.Id)).ValueGeneratedNever();
            }

            if (typeof(ReferenceEntity).IsAssignableFrom(clrType))
            {
                modelBuilder.Entity(clrType).Property(nameof(ReferenceEntity.RowVersion)).IsRowVersion();
                modelBuilder.Entity(clrType).HasIndex(nameof(ReferenceEntity.RowVersion));
            }

            // No cascading deletes on business data unless a configuration says so explicitly.
            foreach (var fk in entityType.GetForeignKeys().Where(fk => fk.DeleteBehavior == DeleteBehavior.Cascade && !fk.IsOwnership))
            {
                if (fk.FindAnnotation(CascadeAllowed) is null)
                {
                    fk.DeleteBehavior = DeleteBehavior.Restrict;
                }
            }
        }
    }

    internal const string CascadeAllowed = "Newrest:CascadeAllowed";
}
