<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Newrest.Pos.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="ClosedXML" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Newrest.Pos.Domain/Newrest.Pos.Domain.csproj" />
    <ProjectReference Include="../Newrest.Pos.Contracts/Newrest.Pos.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Newrest.Pos.Application.Tests" />
  </ItemGroup>
</Project>
