// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Newrest.Pos.Client.Data;

#nullable disable

namespace Newrest.Pos.Client.Data.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    partial class ClientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Newrest.Pos.Client.Data.CacheEntry", b =>
                {
                    b.Property<string>("Kind")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LookupKey")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Kind", "Id");

                    b.HasIndex("Kind", "LookupKey");

                    b.ToTable("Cache");
                });

            modelBuilder.Entity("Newrest.Pos.Client.Data.LocalAccountMovement", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BadgeNumber")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConfirmedOnline")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Synced")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdempotencyKey");

                    b.HasIndex("CashSessionId");

                    b.HasIndex("AccountId", "Synced");

                    b.ToTable("AccountMovements");
                });

            modelBuilder.Entity("Newrest.Pos.Client.Data.LocalCashSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClosedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OpenedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpeningFloat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ZReportId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CashSessions");
                });

            modelBuilder.Entity("Newrest.Pos.Client.Data.LocalSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Newrest.Pos.Client.Data.LocalTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BadgeNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreditedTicketId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DinerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DinerShare")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("IssuedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubsidyAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.HasIndex("CashSessionId", "Sequence");

                    b.HasIndex("DinerId", "BusinessDate");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Newrest.Pos.Client.Data.LocalZReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CashSessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("GeneratedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZNumber")
                        .IsUnique();

                    b.ToTable("ZReports");
                });

            modelBuilder.Entity("Newrest.Pos.Client.Data.OutboxItem", b =>
                {
                    b.Property<long>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SentAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Position");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Outbox");
                });

            modelBuilder.Entity("Newrest.Pos.Client.Data.RegisterState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastZNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OpenSessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegisterStates");
                });
#pragma warning restore 612, 618
        }
    }
}
