namespace Newrest.Pos.Contracts.V1;

public sealed record AccountSummaryDto(Guid Id, Guid ContractId, string Type, decimal Balance, decimal OverdraftLimit,
    decimal AvailableToSpend, bool IsActive);

public sealed record AccountDto(Guid Id, Guid DinerId, string DinerName, string EmployeeNumber, Guid ClientCompanyId,
    Guid ContractId, string Type, decimal Balance, decimal OverdraftLimit, decimal AvailableToSpend, bool IsActive);

public sealed record AccountUpdate(string Type, decimal OverdraftLimit, bool IsActive);

public sealed record MovementDto(Guid Id, Guid AccountId, string Type, decimal Amount, DateTimeOffset OccurredAt,
    decimal BalanceAfter, string? PaymentMethod, string? Comment, string? PerformedBy, Guid? TicketId, Guid? RegisterId,
    Guid? ReversesMovementId, bool IsReversed, bool IsOfflineReplay, bool ExceededOverdraft);

/// <param name="IdempotencyKey">Generated by the caller; replaying the same request returns the original movement.</param>
/// <param name="PaymentMethod">Cash, Card or BankTransfer.</param>
public sealed record TopUpRequest(decimal Amount, string PaymentMethod, Guid IdempotencyKey, string? Comment);

/// <summary>Manual signed correction (+ credit / − debit) with a mandatory reason.</summary>
public sealed record CorrectionRequest(decimal Amount, string Reason, Guid IdempotencyKey);

public sealed record ReversalRequest(string Reason, Guid IdempotencyKey);

/// <summary>Remaining balance given back to the diner (e.g. leaving the company).</summary>
public sealed record RefundRequest(decimal Amount, string PaymentMethod, string Reason, Guid IdempotencyKey);

public sealed record LedgerResultDto(Guid MovementId, Guid AccountId, decimal Amount, decimal BalanceAfter, bool WasDuplicate);
