<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Newrest.Pos.Devices</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Ports" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Newrest.Pos.Devices.Tests" />
  </ItemGroup>
</Project>
